await game.dsmacros.executeMacroFromCompendium("ShareAbility", {
  name: "",
  resourceCost: undefined | 0,
  flavorText: undefined | "",
  type: "",
  keywords: "",
  isKit: undefined | false,
  distance: "",
  target: "",
  trigger: undefined | "",
  powerRollStat: undefined | "",
  tier1Effect: undefined | "",
  tier2Effect: undefined | "",
  tier3Effect: undefined | "",
  effect: undefined | "" | ``,
  extraResourceCost: undefined | "",
  extraResourceEffect: undefined | "" | ``,
  persistentCost: undefined | 0,
  persistentEffect: undefined | ""| ``,
  getResourceCostFunc: async function() { },
  getAllowedEdgeBaneFunc: async function(resourceCost) { },
  getExtraDamageFunc: async function() { },
  onUseFunc: async function() { },
  onSurgeFunc: async function(damageSurges, potencySurges) { }
});
      